update RDB$FIELDS set
RDB$FIELD_LENGTH = 10,
RDB$CHARACTER_LENGTH = 10
where RDB$FIELD_NAME = 'RDB$464'


update RDB$FIELDS set
RDB$FIELD_LENGTH = 10,
RDB$CHARACTER_LENGTH = 10
where RDB$FIELD_NAME = 'RDB$513'