INSERT INTO PARAMETROS (PARAMETRO, DESCRICAO, CONFIGURADO, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9) VALUES ('carterinha', 'Qual Empresa  Ex :  SERRA ou PIRAMIDE', NULL, 'PIRAMIDE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

