INSERT INTO FAMILIA (ID_FAMILIA, DESCRICAO) VALUES ('1', 'URNAS');
INSERT INTO FAMILIA (ID_FAMILIA, DESCRICAO) VALUES ('3', 'MATERIAIS FUNERÁRIO');
INSERT INTO FAMILIA (ID_FAMILIA, DESCRICAO) VALUES ('4', 'COROA DE FLORES');
INSERT INTO FAMILIA (ID_FAMILIA, DESCRICAO) VALUES ('5', 'SERVIÇOS');

