INSERT INTO PARAMETROS (PARAMETRO, DESCRICAO, CONFIGURADO, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9) VALUES ('Valor Dep', 'Valor Cobrado Por Dependente Plano Economico/Mensal', NULL, '1.5', 'MENSAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PARAMETROS (PARAMETRO, DESCRICAO, CONFIGURADO, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9) VALUES ('Valor Dep.', NULL, NULL, '1.8', 'TRIMESTRAL', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PARAMETROS (PARAMETRO, DESCRICAO, CONFIGURADO, PARAMETRO1, PARAMETRO2, PARAMETRO3, PARAMETRO4, PARAMETRO5, PARAMETRO6, PARAMETRO7, PARAMETRO8, PARAMETRO9) VALUES ('Valor Dep,', NULL, NULL, '1.9', '7 FALECIMENTO', NULL, NULL, NULL, NULL, NULL, NULL, NULL);


