CREATE PROCEDURE SP_DECL_OBITOS_MENOS (
    pid integer)
returns (
    codigo integer,
    falecido varchar(100),
    sexo char(1),
    cor varchar(40),
    data_nasc date,
    idade integer,
    estado_civil varchar(30),
    profissao varchar(40),
    naturalidade varchar(80),
    endereco_fal varchar(100),
    numero varchar(5),
    bairro varchar(40),
    cidade varchar(40),
    uf char(2),
    nome_pai varchar(80),
    nome_mae varchar(80),
    estcivil_pai varchar(30),
    estcivil_mae varchar(30),
    endereco_pais varchar(100),
    numero_pais varchar(5),
    bairro_pais varchar(40),
    cidade_pais varchar(40),
    uf_pais char(2),
    deixa_bens char(1),
    deixa_testamento char(1),
    eleitor char(1),
    cidade_eleitoral varchar(40),
    cemiterio varchar(100),
    data_sep date,
    hora_sep time,
    local_fal varchar(80),
    data_fal date,
    hora_fal time,
    medico_1 varchar(80),
    medico_2 varchar(80),
    crm_1 varchar(15),
    crm_2 varchar(15),
    causa_morte varchar(300),
    obs varchar(200),
    nupcias varchar(80),
    data_casamento date,
    conjuge varchar(80),
    livro varchar(5),
    folhas varchar(5),
    num varchar(10),
    doc_apresentado varchar(400),
    registro varchar(100),
    endereco_reg varchar(100),
    declarante varchar(80),
    rg_cpf varchar(20),
    profissao_decl varchar(30),
    grau_parentesco varchar(30),
    fone_decl varchar(14),
    endereco_decl varchar(100),
    natural_pai varchar(80),
    profissao_pai varchar(40),
    natural_mae varchar(80),
    profissao_mae varchar(40),
    zona_eleitoral varchar(40),
    zona_numero varchar(40),
    secao varchar(20),
    estcivil_decl varchar(30),
    reservista varchar(15),
    categoria varchar(10),
    categoria_num varchar(10),
    serie_reserv varchar(10),
    csm varchar(10),
    rm varchar(10),
    nupcias_2 varchar(80),
    data_casamento_2 date,
    conjuge_2 varchar(80),
    livro_2 varchar(5),
    folhas_2 varchar(5),
    num_2 varchar(10),
    agencia varchar(25),
    preco double precision,
    notafiscal smallint,
    tipo_obito varchar(10),
    cpf_fal varchar(15),
    rg_fal varchar(15),
    ssp char(15),
    expedicao date,
    cartorio_end integer,
    funcionario varchar(80),
    tipo char(1),
    imss char(1),
    n_beneficio varchar(30),
    declarante_nacionalidade varchar(30),
    falecido_estcivil varchar(30),
    data_declaracao date,
    cpf_declarante varchar(14),
    ssp_declarante varchar(15),
    nacionalidade varchar(30),
    linha integer,
    cep varchar(10),
    pis varchar(14),
    ctps varchar(7),
    ctps_serie varchar(5),
    ctps_uf varchar(2),
    fal_livro varchar(5),
    fal_folha varchar(5),
    fal_num varchar(10),
    fal_id_cartorio integer,
    fal_cartorio varchar(100),
    fal_cartorio_end varchar(100),
    fal_cartorio_cidade varchar(100))
as
declare variable i integer;
BEGIN

   I=0;
   LINHA=1;

   SELECT f.NOME FROM FUNCIONARIOS f INNER JOIN OBITOS o ON
     o.COD_FUNCIONARIO = f.COD_FUNCIONARIO WHERE (o.ID = :PID)
   INTO :FUNCIONARIO;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC,(udf_age(DATA_NASC)-1), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , DECLA_NACIONALIDADE, FALEC_ESTCIVIL, DATA_SISTEMA , CPF_DECLARANTE, SSP_DECLARANTE, NACIONALIDADE , CEP,
        PIS,CTPS,CTPS_SERIE ,CTPS_UF ,FAL_LIVRO ,FAL_FOLHA ,FAL_NUM ,FAL_ID_CARTORIO ,FAL_CARTORIO,FAL_CARTORIO_END, FAL_CARTORIO_CIDADE

        FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:declarante_nacionalidade,:falecido_estcivil, :DATA_DECLARACAO , :CPF_DECLARANTE, :SSP_DECLARANTE, :NACIONALIDADE, :CEP ,
        :PIS,:CTPS,:CTPS_SERIE ,:CTPS_UF ,:FAL_LIVRO ,:FAL_FOLHA ,:FAL_NUM ,:FAL_ID_CARTORIO ,:FAL_CARTORIO,:FAL_CARTORIO_END,:FAL_CARTORIO_CIDADE
   DO
   BEGIN
  SUSPEND;
END
   LINHA=2;

   SELECT f.NOME FROM FUNCIONARIOS f INNER JOIN OBITOS o ON
     o.COD_FUNCIONARIO = f.COD_FUNCIONARIO WHERE (o.ID = :PID)
   INTO :FUNCIONARIO;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, (udf_age(DATA_NASC)-1), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , DECLA_NACIONALIDADE, FALEC_ESTCIVIL, DATA_SISTEMA , CPF_DECLARANTE, SSP_DECLARANTE, NACIONALIDADE , CEP,
        PIS,CTPS,CTPS_SERIE ,CTPS_UF ,FAL_LIVRO ,FAL_FOLHA ,FAL_NUM ,FAL_ID_CARTORIO ,FAL_CARTORIO,FAL_CARTORIO_END, FAL_CARTORIO_CIDADE

        FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:declarante_nacionalidade,:falecido_estcivil, :DATA_DECLARACAO , :CPF_DECLARANTE, :SSP_DECLARANTE, :NACIONALIDADE, :CEP ,
        :PIS,:CTPS,:CTPS_SERIE ,:CTPS_UF ,:FAL_LIVRO ,:FAL_FOLHA ,:FAL_NUM ,:FAL_ID_CARTORIO ,:FAL_CARTORIO,:FAL_CARTORIO_END,:FAL_CARTORIO_CIDADE
   DO
   BEGIN
  SUSPEND;
END

   LINHA=3;

   SELECT f.NOME FROM FUNCIONARIOS f INNER JOIN OBITOS o ON
     o.COD_FUNCIONARIO = f.COD_FUNCIONARIO WHERE (o.ID = :PID)
   INTO :FUNCIONARIO;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, (udf_age(DATA_NASC)-1), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , DECLA_NACIONALIDADE, FALEC_ESTCIVIL, DATA_SISTEMA , CPF_DECLARANTE, SSP_DECLARANTE, NACIONALIDADE , CEP,
        PIS,CTPS,CTPS_SERIE ,CTPS_UF ,FAL_LIVRO ,FAL_FOLHA ,FAL_NUM ,FAL_ID_CARTORIO ,FAL_CARTORIO,FAL_CARTORIO_END, FAL_CARTORIO_CIDADE

        FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:declarante_nacionalidade,:falecido_estcivil, :DATA_DECLARACAO , :CPF_DECLARANTE, :SSP_DECLARANTE, :NACIONALIDADE, :CEP ,
        :PIS,:CTPS,:CTPS_SERIE ,:CTPS_UF ,:FAL_LIVRO ,:FAL_FOLHA ,:FAL_NUM ,:FAL_ID_CARTORIO ,:FAL_CARTORIO,:FAL_CARTORIO_END,:FAL_CARTORIO_CIDADE
   DO
   BEGIN
  SUSPEND;
END
   LINHA=4;

   SELECT f.NOME FROM FUNCIONARIOS f INNER JOIN OBITOS o ON
     o.COD_FUNCIONARIO = f.COD_FUNCIONARIO WHERE (o.ID = :PID)
   INTO :FUNCIONARIO;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, (udf_age(DATA_NASC)-1), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , DECLA_NACIONALIDADE, FALEC_ESTCIVIL, DATA_SISTEMA , CPF_DECLARANTE, SSP_DECLARANTE, NACIONALIDADE , CEP,
        PIS,CTPS,CTPS_SERIE ,CTPS_UF ,FAL_LIVRO ,FAL_FOLHA ,FAL_NUM ,FAL_ID_CARTORIO ,FAL_CARTORIO,FAL_CARTORIO_END, FAL_CARTORIO_CIDADE

        FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:declarante_nacionalidade,:falecido_estcivil, :DATA_DECLARACAO , :CPF_DECLARANTE, :SSP_DECLARANTE, :NACIONALIDADE, :CEP ,
        :PIS,:CTPS,:CTPS_SERIE ,:CTPS_UF ,:FAL_LIVRO ,:FAL_FOLHA ,:FAL_NUM ,:FAL_ID_CARTORIO ,:FAL_CARTORIO,:FAL_CARTORIO_END,:FAL_CARTORIO_CIDADE
   DO
   BEGIN
  SUSPEND;
END
   LINHA=5;

   SELECT f.NOME FROM FUNCIONARIOS f INNER JOIN OBITOS o ON
     o.COD_FUNCIONARIO = f.COD_FUNCIONARIO WHERE (o.ID = :PID)
   INTO :FUNCIONARIO;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, (udf_age(DATA_NASC)-1), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , DECLA_NACIONALIDADE, FALEC_ESTCIVIL, DATA_SISTEMA , CPF_DECLARANTE, SSP_DECLARANTE, NACIONALIDADE , CEP,
        PIS,CTPS,CTPS_SERIE ,CTPS_UF ,FAL_LIVRO ,FAL_FOLHA ,FAL_NUM ,FAL_ID_CARTORIO ,FAL_CARTORIO,FAL_CARTORIO_END, FAL_CARTORIO_CIDADE

        FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:declarante_nacionalidade,:falecido_estcivil, :DATA_DECLARACAO , :CPF_DECLARANTE, :SSP_DECLARANTE, :NACIONALIDADE, :CEP ,
        :PIS,:CTPS,:CTPS_SERIE ,:CTPS_UF ,:FAL_LIVRO ,:FAL_FOLHA ,:FAL_NUM ,:FAL_ID_CARTORIO ,:FAL_CARTORIO,:FAL_CARTORIO_END,:FAL_CARTORIO_CIDADE
   DO
   BEGIN
  SUSPEND;
END
END
