set term ^;
CREATE OR ALTER PROCEDURE SP_DEC_NATIMORTO (
    PID INTEGER)
RETURNS (
    CODIGO INTEGER,
    FALECIDO VARCHAR(100),
    SEXO CHAR(1),
    COR VARCHAR(40),
    DATA_NASC DATE,
    IDADE INTEGER,
    ESTADO_CIVIL VARCHAR(30),
    PROFISSAO VARCHAR(40),
    NATURALIDADE VARCHAR(80),
    ENDERECO_FAL VARCHAR(100),
    NUMERO VARCHAR(5),
    BAIRRO VARCHAR(40),
    CIDADE VARCHAR(40),
    UF CHAR(2),
    NOME_PAI VARCHAR(80),
    NOME_MAE VARCHAR(80),
    ESTCIVIL_PAI VARCHAR(30),
    ESTCIVIL_MAE VARCHAR(30),
    ENDERECO_PAIS VARCHAR(100),
    NUMERO_PAIS VARCHAR(5),
    BAIRRO_PAIS VARCHAR(40),
    CIDADE_PAIS VARCHAR(40),
    UF_PAIS CHAR(2),
    DEIXA_BENS CHAR(1),
    DEIXA_TESTAMENTO CHAR(1),
    ELEITOR CHAR(1),
    CIDADE_ELEITORAL VARCHAR(40),
    CEMITERIO VARCHAR(100),
    DATA_SEP DATE,
    HORA_SEP TIME,
    LOCAL_FAL VARCHAR(80),
    DATA_FAL DATE,
    HORA_FAL TIME,
    MEDICO_1 VARCHAR(80),
    MEDICO_2 VARCHAR(80),
    CRM_1 VARCHAR(15),
    CRM_2 VARCHAR(15),
    CAUSA_MORTE VARCHAR(300),
    OBS VARCHAR(200),
    NUPCIAS VARCHAR(80),
    DATA_CASAMENTO DATE,
    CONJUGE VARCHAR(80),
    LIVRO VARCHAR(5),
    FOLHAS VARCHAR(5),
    NUM VARCHAR(5),
    DOC_APRESENTADO VARCHAR(400),
    REGISTRO VARCHAR(100),
    ENDERECO_REG VARCHAR(100),
    DECLARANTE VARCHAR(80),
    RG_CPF VARCHAR(20),
    PROFISSAO_DECL VARCHAR(30),
    GRAU_PARENTESCO VARCHAR(30),
    FONE_DECL VARCHAR(13),
    ENDERECO_DECL VARCHAR(100),
    NATURAL_PAI VARCHAR(80),
    PROFISSAO_PAI VARCHAR(40),
    NATURAL_MAE VARCHAR(80),
    PROFISSAO_MAE VARCHAR(40),
    ZONA_ELEITORAL VARCHAR(40),
    ZONA_NUMERO VARCHAR(40),
    SECAO VARCHAR(20),
    ESTCIVIL_DECL VARCHAR(20),
    RESERVISTA VARCHAR(15),
    CATEGORIA VARCHAR(10),
    CATEGORIA_NUM VARCHAR(10),
    SERIE_RESERV VARCHAR(10),
    CSM VARCHAR(10),
    RM VARCHAR(10),
    NUPCIAS_2 VARCHAR(80),
    DATA_CASAMENTO_2 DATE,
    CONJUGE_2 VARCHAR(80),
    LIVRO_2 VARCHAR(5),
    FOLHAS_2 VARCHAR(5),
    NUM_2 VARCHAR(5),
    AGENCIA VARCHAR(25),
    PRECO DOUBLE PRECISION,
    NOTAFISCAL SMALLINT,
    TIPO_OBITO VARCHAR(10),
    CPF_FAL VARCHAR(15),
    RG_FAL VARCHAR(15),
    SSP CHAR(6),
    EXPEDICAO DATE,
    CARTORIO_END INTEGER,
    FUNCIONARIO VARCHAR(80),
    TIPO CHAR(1),
    IMSS CHAR(1),
    N_BENEFICIO VARCHAR(30),
    AVO_MATERNO_PAI VARCHAR(80),
    AVO_PATERNO_PAI VARCHAR(80),
    NUPCIAS_PAI VARCHAR(80),
    DATA_CASAMENTO_PAI DATE,
    LIVRO_PAI VARCHAR(5),
    FOLHAS_PAI VARCHAR(5),
    NUM_PAI VARCHAR(5),
    OBSERVACAO_PAI VARCHAR(80),
    AVO_MATERNO_PAI1 VARCHAR(80),
    AVO_PATERNO_PAI1 VARCHAR(80),
    LOCAL_NASCCTO VARCHAR(80),
    LINHA INTEGER )

AS
DECLARE VARIABLE I INTEGER;
BEGIN

   I=0;





   SELECT f.NOME FROM FUNCIONARIOS f INNER JOIN OBITOS o ON 

     o.COD_FUNCIONARIO = f.COD_FUNCIONARIO WHERE (o.ID = :PID) 

   INTO :FUNCIONARIO; 
   LINHA=1;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , AVO_MATERNO_PAI, AVO_PATERNO_PAI, NUPCIAS_PAI , DATA_CASAMENTO_PAI , LIVRO_PAI , FOLHAS_PAI
        , NUM_PAI , OBSERVACAO_PAI ,AVO_MATERNO_PAI , AVO_PATERNO_PAI,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1 ,LOCAL_NASCCTO

        FROM OBITOS WHERE (ID = :PID)

   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:AVO_MATERNO_PAI,:AVO_PATERNO_PAI,:NUPCIAS_PAI ,:DATA_CASAMENTO_PAI ,:LIVRO_PAI ,:FOLHAS_PAI
        ,:NUM_PAI , :OBSERVACAO_PAI ,:AVO_MATERNO_PAI ,:AVO_PATERNO_PAI ,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1,:LOCAL_NASCCTO

   DO

   BEGIN

  SUSPEND;

END

   LINHA=2;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , AVO_MATERNO_PAI, AVO_PATERNO_PAI, NUPCIAS_PAI , DATA_CASAMENTO_PAI , LIVRO_PAI , FOLHAS_PAI
        , NUM_PAI , OBSERVACAO_PAI ,AVO_MATERNO_PAI , AVO_PATERNO_PAI,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1 ,LOCAL_NASCCTO

        FROM OBITOS WHERE (ID = :PID)

   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:AVO_MATERNO_PAI,:AVO_PATERNO_PAI,:NUPCIAS_PAI ,:DATA_CASAMENTO_PAI ,:LIVRO_PAI ,:FOLHAS_PAI
        ,:NUM_PAI , :OBSERVACAO_PAI ,:AVO_MATERNO_PAI ,:AVO_PATERNO_PAI ,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1,:LOCAL_NASCCTO

   DO

   BEGIN

  SUSPEND;

END

   LINHA=3;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , AVO_MATERNO_PAI, AVO_PATERNO_PAI, NUPCIAS_PAI , DATA_CASAMENTO_PAI , LIVRO_PAI , FOLHAS_PAI
        , NUM_PAI , OBSERVACAO_PAI ,AVO_MATERNO_PAI , AVO_PATERNO_PAI,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1 ,LOCAL_NASCCTO

        FROM OBITOS WHERE (ID = :PID)

   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:AVO_MATERNO_PAI,:AVO_PATERNO_PAI,:NUPCIAS_PAI ,:DATA_CASAMENTO_PAI ,:LIVRO_PAI ,:FOLHAS_PAI
        ,:NUM_PAI , :OBSERVACAO_PAI ,:AVO_MATERNO_PAI ,:AVO_PATERNO_PAI ,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1,:LOCAL_NASCCTO

   DO

   BEGIN

  SUSPEND;

END

   LINHA=4;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , AVO_MATERNO_PAI, AVO_PATERNO_PAI, NUPCIAS_PAI , DATA_CASAMENTO_PAI , LIVRO_PAI , FOLHAS_PAI
        , NUM_PAI , OBSERVACAO_PAI ,AVO_MATERNO_PAI , AVO_PATERNO_PAI,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1 ,LOCAL_NASCCTO

        FROM OBITOS WHERE (ID = :PID)

   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:AVO_MATERNO_PAI,:AVO_PATERNO_PAI,:NUPCIAS_PAI ,:DATA_CASAMENTO_PAI ,:LIVRO_PAI ,:FOLHAS_PAI
        ,:NUM_PAI , :OBSERVACAO_PAI ,:AVO_MATERNO_PAI ,:AVO_PATERNO_PAI ,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1,:LOCAL_NASCCTO

   DO

   BEGIN

  SUSPEND;

END

   LINHA=5;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, SECAO, DECLA_ESTCIVIL,RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, CPF_FALECIDO, RG_FALECIDO
        , SSP_FALECIDO, DTA_EXPDICAO, ID_CARTORIO, TIPO, IMSS, N_BENEFICIO
        , AVO_MATERNO_PAI, AVO_PATERNO_PAI, NUPCIAS_PAI , DATA_CASAMENTO_PAI , LIVRO_PAI , FOLHAS_PAI
        , NUM_PAI , OBSERVACAO_PAI ,AVO_MATERNO_PAI , AVO_PATERNO_PAI,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1 ,LOCAL_NASCCTO

        FROM OBITOS WHERE (ID = :PID)

   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:secao,:estcivil_decl,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:CPF_FAL,:RG_FAL,:SSP,:EXPEDICAO,:CARTORIO_END,:TIPO
        ,:IMSS,:n_beneficio,:AVO_MATERNO_PAI,:AVO_PATERNO_PAI,:NUPCIAS_PAI ,:DATA_CASAMENTO_PAI ,:LIVRO_PAI ,:FOLHAS_PAI
        ,:NUM_PAI , :OBSERVACAO_PAI ,:AVO_MATERNO_PAI ,:AVO_PATERNO_PAI ,AVO_MATERNO_PAI1 , AVO_PATERNO_PAI1,:LOCAL_NASCCTO

   DO

   BEGIN

  SUSPEND;

END
END
