CREATE OR ALTER PROCEDURE SP_N_OBITOS (
    pid integer)
returns (
    codigo integer,
    falecido varchar(100),
    sexo char(1),
    cor varchar(40),
    data_nasc date,
    idade integer,
    estado_civil varchar(30),
    profissao varchar(40),
    naturalidade varchar(40),
    endereco_fal varchar(100),
    numero varchar(5),
    bairro varchar(40),
    cidade varchar(40),
    uf char(2),
    nome_pai varchar(80),
    nome_mae varchar(80),
    estcivil_pai varchar(30),
    estcivil_mae varchar(30),
    endereco_pais varchar(100),
    numero_pais varchar(5),
    bairro_pais varchar(40),
    cidade_pais varchar(40),
    uf_pais char(2),
    deixa_bens char(1),
    deixa_testamento char(1),
    eleitor char(1),
    cidade_eleitoral varchar(40),
    cemiterio varchar(100),
    data_sep date,
    hora_sep time,
    local_fal varchar(160),
    data_fal date,
    hora_fal time,
    medico_1 varchar(80),
    medico_2 varchar(80),
    crm_1 varchar(15),
    crm_2 varchar(15),
    causa_morte varchar(100),
    obs varchar(200),
    nupcias varchar(80),
    data_casamento date,
    conjuge varchar(80),
    livro varchar(5),
    folhas varchar(5),
    num varchar(10),
    doc_apresentado varchar(200),
    registro varchar(100),
    declarante varchar(80),
    rg_cpf varchar(20),
    profissao_decl varchar(30),
    grau_parentesco varchar(30),
    fone_decl varchar(14),
    endereco_decl varchar(100),
    linha integer,
    nacionalidade varchar(30),
    cpf_declarante varchar(14))
as
declare variable i integer;
BEGIN

   I=0;

   LINHA=1;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL ,NACIONALIDADE ,CPF_DECLARANTE FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL , :NACIONALIDADE ,:CPF_DECLARANTE
   DO
   BEGIN
  SUSPEND;
END

   LINHA=2;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL ,NACIONALIDADE ,CPF_DECLARANTE FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL ,:NACIONALIDADE ,:CPF_DECLARANTE
   DO
   BEGIN
  SUSPEND;
END

   LINHA=3;
   FOR SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, (udf_age(DATA_NASC)-1), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL ,NACIONALIDADE ,CPF_DECLARANTE FROM OBITOS WHERE (ID = :PID)
   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL ,:NACIONALIDADE ,:CPF_DECLARANTE
   DO
   BEGIN
  SUSPEND;
END


END
