SET TERM ^ ;
ALTER PROCEDURE SP_ORDEM_SERV (
    PID Integer )
RETURNS (
    CODIGO Integer,
    FALECIDO Varchar(100),
    SEXO Char(1),
    COR Varchar(40),
    DATA_NASC Date,
    IDADE Integer,
    ESTADO_CIVIL Varchar(30),
    PROFISSAO Varchar(40),
    NATURALIDADE Varchar(40),
    ENDERECO_FAL Varchar(100),
    NUMERO Varchar(5),
    BAIRRO Varchar(40),
    CIDADE Varchar(40),
    UF Char(2),
    NOME_PAI Varchar(80),
    NOME_MAE Varchar(80),
    ESTCIVIL_PAI Varchar(30),
    ESTCIVIL_MAE Varchar(30),
    ENDERECO_PAIS Varchar(100),
    NUMERO_PAIS Varchar(5),
    BAIRRO_PAIS Varchar(40),
    CIDADE_PAIS Varchar(40),
    UF_PAIS Char(2),
    DEIXA_BENS Char(1),
    DEIXA_TESTAMENTO Char(1),
    ELEITOR Char(1),
    CIDADE_ELEITORAL Varchar(40),
    CEMITERIO Varchar(100),
    DATA_SEP Date,
    HORA_SEP Time,
    LOCAL_FAL Varchar(80),
    DATA_FAL Date,
    HORA_FAL Time,
    MEDICO_1 Varchar(80),
    MEDICO_2 Varchar(80),
    CRM_1 Varchar(15),
    CRM_2 Varchar(15),
    CAUSA_MORTE Varchar(100),
    OBS Varchar(200),
    NUPCIAS Varchar(80),
    DATA_CASAMENTO Date,
    CONJUGE Varchar(80),
    LIVRO Varchar(5),
    FOLHAS Varchar(5),
    NUM Varchar(5),
    DOC_APRESENTADO Varchar(200),
    REGISTRO Varchar(100),
    ENDERECO_REG Varchar(100),
    DECLARANTE Varchar(80),
    RG_CPF Varchar(20),
    PROFISSAO_DECL Varchar(30),
    GRAU_PARENTESCO Varchar(30),
    FONE_DECL Varchar(13),
    ENDERECO_DECL Varchar(100),
    NATURAL_PAI Varchar(80),
    PROFISSAO_PAI Varchar(40),
    NATURAL_MAE Varchar(80),
    PROFISSAO_MAE Varchar(40),
    ZONA_ELEITORAL Varchar(40),
    ZONA_NUMERO Varchar(20),
    RESERVISTA Varchar(15),
    CATEGORIA Varchar(20),
    CATEGORIA_NUM Varchar(10),
    SERIE_RESERV Varchar(10),
    CSM Varchar(10),
    RM Varchar(10),
    NUPCIAS_2 Varchar(80),
    DATA_CASAMENTO_2 Date,
    CONJUGE_2 Varchar(80),
    LIVRO_2 Varchar(5),
    FOLHAS_2 Varchar(5),
    NUM_2 Varchar(5),
    AGENCIA Varchar(25),
    PRECO Double precision,
    NOTAFISCAL Smallint,
    TIPO_OBITO Varchar(10),
    COD_FUN Integer,
    COD_SOC Integer,
    FUNCIONARIO Varchar(100),
    SOCIO Varchar(100),
    GRUPO Char(1),
    INSCRICAO Integer )
AS
begin

   SELECT CODIGO, FALECIDO, SEXO, COR, DATA_NASC, udf_age(DATA_NASC), ESTADO_CIVIL, PROFISSAO, NATURALIDADE
        , ENDERECO_FAL, NUMERO, BAIRRO, CIDADE, UF, NOME_PAI, NOME_MAE, ESTCIVIL_PAI
        , ESTCIVIL_MAE, ENDERECO_PAIS, NUMERO_PAIS, BAIRRO_PAIS, CIDADE_PAIS, UF_PAIS
        , DEIXA_BENS, DEIXA_TESTAMENTO, ELEITOR, CIDADE_ELEITORAL, CEMITERIO, DATA_SEP
        , HORA_SEP, LOCAL_FAL, DATA_FAL, HORA_FAL, MEDICO_1, MEDICO_2, CRM_1, CRM_2
        , CAUSA_MORTE, OBS, NUPCIAS, DATA_CASAMENTO, CONJUGE, LIVRO, FOLHAS, NUM
        , DOC_APRESENTADO, REGISTRO, ENDERECO , DECLARANTE, RG_CPF, PROFISSAO_DECL, GRAU_PARENTESCO
        , FONE_DECL, ENDERECO_DECL, NATURAL_PAI, PROFISSAO_PAI, NATURAL_MAE, PROFISSAO_MAE
        , ZONA_ELEITORAL, ZONA_NUMERO, RESERVISTA, CATEGORIA, CATEGORIA_NUM, SERIE_RESERV
        , CSM, RM, NUPCIAS_2, DATA_CASAMENTO_2, CONJUGE_2, LIVRO_2, FOLHAS_2, NUM_2, AGENCIA
        , VALOR_SERVICO, NOTAFISCAL, TIPO_OBITO, COD_FUNCIONARIO, ID_SOCIO, GRUPO, INSCRICAO
        FROM OBITOS WHERE (ID = :PID)

   INTO:CODIGO,:FALECIDO,:SEXO,:COR,:DATA_NASC,:IDADE,:ESTADO_CIVIL,:PROFISSAO,:NATURALIDADE
        ,:ENDERECO_FAL,:NUMERO,:BAIRRO,:CIDADE,:UF,:NOME_PAI,:NOME_MAE,:ESTCIVIL_PAI
        ,:ESTCIVIL_MAE,:ENDERECO_PAIS,:NUMERO_PAIS,:BAIRRO_PAIS,:CIDADE_PAIS,:UF_PAIS
        ,:DEIXA_BENS,:DEIXA_TESTAMENTO,:ELEITOR,:CIDADE_ELEITORAL,:CEMITERIO,:DATA_SEP
        ,:HORA_SEP,:LOCAL_FAL,:DATA_FAL,:HORA_FAL,:MEDICO_1,:MEDICO_2,:CRM_1,:CRM_2
        ,:CAUSA_MORTE,:OBS,:NUPCIAS,:DATA_CASAMENTO,:CONJUGE,:LIVRO,:FOLHAS,:NUM
        ,:DOC_APRESENTADO,:REGISTRO,:endereco_reg,:DECLARANTE,:RG_CPF,:PROFISSAO_DECL,:GRAU_PARENTESCO
        ,:FONE_DECL,:ENDERECO_DECL,:NATURAL_PAI,:PROFISSAO_PAI,:NATURAL_MAE,:PROFISSAO_MAE
        ,:ZONA_ELEITORAL,:ZONA_NUMERO,:RESERVISTA,:CATEGORIA,:CATEGORIA_NUM,:SERIE_RESERV
        ,:CSM,:RM,:NUPCIAS_2,:DATA_CASAMENTO_2,:CONJUGE_2,:LIVRO_2,:FOLHAS_2,:NUM_2,:AGENCIA,:PRECO
        ,:NOTAFISCAL,:TIPO_OBITO,:cod_fun,:cod_soc,:grupo,:inscricao;

  SELECT NOME FROM funcionarios WHERE COD_FUNCIONARIO = :cod_fun
   into :funcionario;

   SELECT NOME_SOCIO FROM socios WHERE ID_SOCIO = :cod_soc
   into :SOCIO;

   suspend;

END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE SP_ORDEM_SERV TO  SYSDBA;

